name: Create Github Release

on:
    push:
        tags:
            - 'v*'

jobs:
    build-and-test:
        uses: "./.github/workflows/compile-and-test.yml"
    release:
        runs-on: ubuntu-latest
        needs: [build-and-test]
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/download-artifact@v4
              with:
                run-id: ${{ github.run_id }}
                github-token: ${{ secrets.GITHUB_TOKEN }}
                name: binaries
                path: |
                    bin
            - name: Create Release
              uses: softprops/action-gh-release@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref_name }}
                  prerelease: true
                  generate_release_notes: true
                  fail_on_unmatched_files: true
                  files: |
                      bin/*
                      LICENSE